"""Derive the slim CadQuery runtime lock used by the arm64 AgentCore sandbox image.

The full lock (native/cadquery-requirements.txt) follows cadquery's declared dependencies, which include
visualisation and JIT packages (scipy, numba/llvmlite, matplotlib, trame) that no PAI code path imports.
AgentCore Runtime images are limited to 2 GB, so the sandbox image installs only what is imported.

  python3 tools/slim_cadquery_lock.py --python .state/tools/cadquery-2.8.0/bin/python [--check]

1. Runs every native CAD entry point (preset, sweep, sandboxed code, measurement of generated code, STEP
   re-import) under `-X importtime` with the full venv and maps imported modules to distributions.
2. Copies those distributions' blocks, with their original hashes, from the full lock. Nothing is re-resolved.
--check fails if the committed slim lock differs from a fresh derivation.
"""
import argparse
import importlib
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

root = Path(__file__).resolve().parent.parent
FULL, SLIM = root / "native/cadquery-requirements.txt", root / "native/cadquery-runtime-requirements.txt"
# Hard pins of kept distributions that are not imported as top-level modules.
ALWAYS = {"cadquery-ocp-proxy"}
REQ = {"maxMassG": 80, "minWallMm": 3, "edgeDistanceFactor": 1.5, "requireNoInterference": True, "maxEnvelopeMm": [80, 40, 60]}

parser = argparse.ArgumentParser()
parser.add_argument("--python", required=True, help="interpreter of a venv installed from the full lock")
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
native = root / "native"
norm = lambda n: n.lower().replace("_", "-")


def run(tmp, name, argv):
    log = tmp / f"{name}.log"
    with log.open("w") as err:
        r = subprocess.run([args.python, "-I", "-W", "ignore", "-X", "importtime", *argv], stdout=subprocess.DEVNULL, stderr=err, timeout=600)
    if r.returncode:
        raise SystemExit(f"{name} failed with the full venv (exit {r.returncode})")


with tempfile.TemporaryDirectory() as t:
    tmp = Path(t)
    for d in ("a", "s", "src", "g"):
        (tmp / d).mkdir()
    (tmp / "a.json").write_text(json.dumps({"variant": "reference", "requirements": REQ}))
    (tmp / "s.json").write_text(json.dumps({"requirements": REQ, "grid": {"thickness": [3], "width": [60], "plateHeight": [46], "pilotBore": [22.5]}}))
    (tmp / "g.json").write_text(json.dumps({"requirements": REQ, "codeSha256": "derivation"}))
    run(tmp, "bracket", [str(native / "cad_bracket.py"), "--input", str(tmp / "a.json"), "--output", str(tmp / "a")])
    run(tmp, "sweep", [str(native / "cad_sweep.py"), "--input", str(tmp / "s.json"), "--output", str(tmp / "s")])
    run(tmp, "sandbox", [str(native / "cad_sandbox.py"), "--code", str(native / "cad_template.py"), "--output", str(tmp / "src")])
    run(tmp, "generated", [str(native / "cad_generated.py"), "--input", str(tmp / "g.json"), "--source", str(tmp / "src"), "--output", str(tmp / "g")])
    run(tmp, "reopen", [str(native / "cad_reopen.py"), str(tmp / "a/part.step"), str(tmp / "reopen.json")])
    modules = set()
    for log in tmp.glob("*.log"):
        for line in log.read_text().splitlines():
            m = re.match(r"import time:\s+\d+ \|\s+\d+ \|\s*(\S+)", line)
            if m:
                modules.add(m.group(1).split(".")[0])
    mapping = json.loads(subprocess.run([args.python, "-I", "-c", "import importlib.metadata as m, json; print(json.dumps(m.packages_distributions()))"],
                                        capture_output=True, text=True, check=True).stdout)
used = {norm(d) for mod in modules for d in mapping.get(mod, [])} | ALWAYS
blocks = re.split(r"\n(?=[A-Za-z0-9_.\-]+==)", FULL.read_text())
kept = {norm(m.group(1)): b.rstrip() for b in blocks if (m := re.match(r"([A-Za-z0-9_.\-]+)==", b)) and norm(m.group(1)) in used}
if used - set(kept):
    raise SystemExit(f"imported distributions missing from the full lock: {sorted(used - set(kept))}")
text = ("# Runtime subset of native/cadquery-requirements.txt for the AgentCore sandbox image (arm64, <2 GB).\n"
        "# Generated by tools/slim_cadquery_lock.py from measured imports of every native CAD entry point;\n"
        "# blocks and hashes are copied verbatim from the full lock. Install with --require-hashes --no-deps.\n"
        + "\n".join(kept[n] for n in sorted(kept)) + "\n")
if args.check:
    if SLIM.read_text() != text:
        raise SystemExit("native/cadquery-runtime-requirements.txt is stale; rerun tools/slim_cadquery_lock.py")
    print(json.dumps({"slimLock": "up-to-date", "distributions": sorted(kept)}))
else:
    SLIM.write_text(text)
    print(json.dumps({"slimLock": str(SLIM.relative_to(root)), "distributions": sorted(kept)}))
