/** Professional tool survey, not an assertion that every native adapter is connected. */
export const toolCatalog = {
  researchedAt: "2026-09-30",
  tools: [
    { id: "blender", name: "Blender", version: "5.2.2 LTS", role: "Scene, assets, visual geometry and camera evidence", status: "integrated", nativeArtifacts: [".blend", ".glb", ".png"], source: "https://www.blender.org/download/", boundary: "Meshes and static visibility do not establish parametric CAD, dynamics or manufacturability." },
    { id: "freecad", name: "FreeCAD", version: "1.1.4", role: "Parametric engineering geometry, dimensions and assemblies", status: "planned", nativeArtifacts: [".FCStd", ".step"], source: "https://www.freecad.org/features.php", boundary: "Preserve editable native history as well as interchange files; require actual geometric checks." },
    { id: "cadquery", name: "CadQuery", version: "2.8.0 (OCCT 7.9.3)", role: "Executable Python CAD with native B-Rep geometry; NEMA 17 bracket recipe, STEP/STL/GLB/SVG and measured DFM checks", status: "integrated", nativeArtifacts: [".py", ".step", ".brep"], source: "https://cadquery.readthedocs.io/en/latest/importexport.html", boundary: "STEP does not preserve CadQuery's original parametric Python history." },
    { id: "openscad", name: "OpenSCAD", version: "2021.01 (latest stable release endpoint)", role: "Script-driven CSG and configurable parts", status: "survey-only", nativeArtifacts: [".scad", ".stl"], source: "https://openscad.org/about.html", boundary: "Development snapshots are a separate opt-in channel; mesh checks are not B-Rep checks." },
    { id: "solvespace", name: "SolveSpace", version: "3.2", role: "Geometric constraints and mechanism sketches", status: "survey-only", nativeArtifacts: [".slvs", ".step"], source: "https://solvespace.com/features.pl", boundary: "Native constraint and export behavior need conformance tests." },
    { id: "onshape", name: "Onshape", version: "Continuous cloud service", role: "Cloud CAD, assemblies, documents and FeatureScript", status: "planned", nativeArtifacts: ["document/version identity", ".step"], source: "https://onshape-public.github.io/docs/", boundary: "Account authorization, API limits and immutable document versions are required." },
    { id: "fusion", name: "Autodesk Fusion / Inventor", version: "Not verified in this session", role: "Commercial engineering and manufacturing workflows", status: "survey-only", nativeArtifacts: ["native design document", ".step"], source: "https://www.autodesk.com/products/fusion-360/features", boundary: "Official pages returned 403/404; native SDK/account integration has not been verified." },
    { id: "solidworks", name: "SOLIDWORKS", version: "2026 API help reachable; installed version unverified", role: "Professional parametric mechanical design", status: "survey-only", nativeArtifacts: [".SLDPRT", ".SLDASM", ".step"], source: "https://help.solidworks.com/2026/english/api/sldworksapiprogguide/Welcome.htm", boundary: "Help shell reachable, dynamic contents and licensed native automation not validated." },
    { id: "nx", name: "Siemens NX", version: "Installed version unverified", role: "Integrated CAD/CAM and enterprise design-to-manufacturing", status: "survey-only", nativeArtifacts: ["native part", ".step"], source: "https://plm.sw.siemens.com/en-US/nx/", boundary: "Vendor performance claims are not our measurements; license and SDK access remain required." },
    { id: "catia", name: "CATIA", version: "R2026x on official product page", role: "Complex engineering, assemblies and systems design", status: "survey-only", nativeArtifacts: ["native part/assembly", ".step"], source: "https://www.3ds.com/products/catia", boundary: "Platform, license and native automation vary between product lines." },
    { id: "creo", name: "PTC Creo", version: "Installed version unverified", role: "Associative parametric engineering and manufacturing", status: "survey-only", nativeArtifacts: ["native part/assembly", ".step"], source: "https://www.ptc.com/en/products/creo", boundary: "Native SDK and licensed execution have not been validated." },
    { id: "rhino", name: "Rhino / Grasshopper Compute", version: "Installed version unverified", role: "Geometry and computational design via SDK/REST", status: "planned", nativeArtifacts: [".3dm", ".gh"], source: "https://developer.rhino3d.com/guides/compute/", boundary: "Actual execution requires a configured and licensed compute endpoint." },
    { id: "gazebo", name: "Gazebo", version: "Jetty LTS in latest docs", role: "Robotics worlds, sensors, dynamics and ROS integration", status: "planned", nativeArtifacts: [".sdf", ".urdf", "simulation logs"], source: "https://gazebosim.org/docs/latest/", boundary: "Physics and sensor validity require simulator-specific native evaluation." },
    { id: "isaac", name: "Isaac Sim", version: "Latest documentation shell reachable; release not parsed", role: "Robotics simulation and USD scene execution", status: "planned", nativeArtifacts: [".usd", "simulation logs"], source: "https://docs.isaacsim.omniverse.nvidia.com/latest/overview/overview.html", boundary: "GPU, version, licensing and full native experiment conformance remain unverified." },
  ],
} as const;
